[package]
name = "controller"
version = "0.1.0"
cairo-version = "2.11.1"

[[target.lib]]

[[target.starknet-contract]]
sierra = true
casm = true
allowed-libfuncs-list.name = "audited"
build-external-contracts = [
	"openzeppelin::presets::account::AccountUpgradeable",
]

[dependencies]
starknet = "2.11.1"
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria", rev = "a0163821eab6d5d42e3dc63b10ec96e4d7a622e0" }
alexandria_encoding = { git = "https://github.com/keep-starknet-strange/alexandria", rev = "a0163821eab6d5d42e3dc63b10ec96e4d7a622e0" }
alexandria_merkle_tree = { git = "https://github.com/keep-starknet-strange/alexandria", rev = "a0163821eab6d5d42e3dc63b10ec96e4d7a622e0" }
alexandria_data_structures = { git = "https://github.com/keep-starknet-strange/alexandria", rev = "a0163821eab6d5d42e3dc63b10ec96e4d7a622e0" }
openzeppelin = "1.0.0"
garaga = { git = "https://github.com/keep-starknet-strange/garaga", rev = "c3db6b78efc0a4b8eb6a8c06df7f053257728ea7" }

[dev-dependencies]
snforge_std = "0.38.3"
assert_macros = "2.11.1"

[tool.fmt]
max-line-length = 120
sort-module-level-items = true

[scripts]
test = "snforge test"
format = "scarb fmt"
